### ISSUE TITLE
investigate and report bug in wasmer

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#633]
We experience a crash similar to https://github.com/wasmerio/wasmer/issues/2434 in CI. This seems related to high-concurrency.

```
thread 'client::client_tests::wasm::test_memory_user_pub_sub_channels::wasmer' panicked at 'assertion failed: prev.start > max', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler 3.1.1/src/engine/trap/frame_info.rs:224:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:115:5
   3: wasmer_compiler::engine::trap::frame_info::register
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-3.1.1/src/engine/trap/frame_info.rs:224:9
   4: wasmer_compiler::engine::artifact::Artifact::register_frame_info
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-3.1.1/src/engine/artifact.rs:274:21
   5: wasmer_compiler::engine::artifact::Artifact::instantiate
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-3.1.1/src/engine/artifact.rs:374:9
   6: wasmer::sys::module::Module::instantiate
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.1.1/src/sys/module.rs:369:39
   7: wasmer::sys::instance::Instance::new
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.1.1/src/sys/instance.rs:121:26
```

**Comment by ma2bd** [comment]
The issue is showing up any more
